# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

configfile: "config/config.yaml"
include: "rules/common.smk"


module rna_seq:
    snakefile: "module_workflows/rna_seq/Snakefile"
    prefix: "rna_seq"
    config: config["rna_seq"]
use rule * from rna_seq as rna_seq_*
# some rules in the module are shell commands which call a script assuming the workdir is the other workdir. use symlinks for scripts to fix.
CreateSymlinksOfDir1ContentsIntoDir2("module_workflows/rna_seq/scripts/", "scripts/")


rule all:
    input:
        # The first rule should define the default target files
        # Subsequent target rules can be specified below. They should start with all_*.

include: "rules/other.smk"
